language: node_js
node_js: node
services:
- mongodb
addons:
  jwt:
    secure: c8EQCUphwRrj+Dr14GkLE7/5vpxBnOeWMN+iVotFpwlu7F3aPbBY2nzhVvAsa+YCWuIG8+t5ptG/2dbQmjPmFCbzBMN+h4vtlHrkA+1Hm9GrKig1Wwqf70Z/nt8V3WUZubJj6azcf24V/5zJIZZFX1zP9WxJlzlR8NAeZe+0ffeO5/XBFqLi2P0iaY8sqvhnuvjwJEKGc2SsgjOgB3WmYy9YclDF7S5D3dbxCRAOamapcuYquIMFkT/QiTlbZXpZ3yRRmy6RPOgWB04CBir2j6LUea7UHiSmRPPgY1sKuaTfv8RNQrli3G+2ryN4cGAFhnEKgD+uKGmdBvYARv8FV0NrtnZTWE84iX8+yYKWRftIjF7x8lEOe3zGW62XQv9QAN3tZosCJh2YbhiZBCep0TUld68RpyX6/L3ZK1vs0F26r8vA03Sm7OBsEVr7nKmlC/4UNdEH4i+QJOalQvjQ3PxG3PQR/I2r1x/mJ/niCrcFrjR/AE2pT39Gu2/nw4NXEpsTdHFmwf3IuzmfyPYB64YADJdvOak/f0TxbLuCfXmdJqT4zcf9eA/aCRHPm79XdSSZRUZioQiArdYXF/LT9Ai9LzaeDklrUs4szETldblLp7Ta179XV545vJMzhkl8fSnri7PGopYjihCrlQ7ZyNJZHMi0JMiPM2DIqlviOUY=
