language: node_js
node_js: node
services:
- mongodb
env:
  matrix:
  - secure: DalQ8Su/4o2lZx+ztFdRRYSgyKu5XLTJzYV1LqFXVCO1lHyRF1Ey+VXaBuedONKf9+StLcioI2KX06bFs1BZvu8Sco38c2EERoxTV+Ac/Xh8WGYeYSTH/sHwqsroHguEJgY9uqsi5JFgh6bvAcV4qf3yj4jfcisQb1ymgmVSfJZZtN1dIZnZS7dtvURrTPD8xdVDfZ6FbloRJd/GHpA3y0RZ6ynU2dno35euTu/CISU8GF5hq2xcm4Rm4DCs8CZBkghvRl848ssqLRv5aZy5Kp//+Qy6pPKxJfEVaK/xXLxocNMhM2IhEFEy6h0r3vyIpQehWg3I5EzPd9EEaHwd/wx2RbHvBO+N+pCOQPWPsCYrDWEbyB01iE3QlJw9dTaRfcMekS75aJMB3PPV9Q7D8H24UT7OH2iHr3/2bvG+ZMxiVYFsRD4i77yu6tMMRooAWG2IkxP+uITvirWXkHMI/mVqfWoZuGxmMbDimHJEP0cZKzzj13hCC6dRQF/Jer4DFXrlL+Ii1ABbVyC4P8buV3gTl3hHuDeTiI1vCgFFw1cd9V0KTzoYM0BZ9u4K7VC5wlFKOwtrTyzm1kgGVcQUQoxrNFIZSIOPTEOsry0WklIA6lkxF4oMHb42/d70bK/1gB3aYJpJ1JgBJGczveHsQC7X/NHnhxRwSIVYtvEJ9i4=
